### ISSUE TITLE
cannot install from pip

### ISSUE THREAD

**Issue by geofffoster** [Lleyton-Ariton/oddity#1]
Python 3.8.1 (default, Jan  8 2020, 22:29:32) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

pip install git+https://github.com/Lleyton-Ariton/oddity.git
Collecting git+https://github.com/Lleyton-Ariton/oddity.git
  Cloning https://github.com/Lleyton-Ariton/oddity.git to /tmp/pip-req-build-f26w_2py
  Running command git clone -q https://github.com/Lleyton-Ariton/oddity.git /tmp/pip-req-build-f26w_2py
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in /home/geoff/anaconda3/envs/zwift/lib/python3.8/site-packages (from oddity==0.1.0) (1.18.5)
Building wheels for collected packages: oddity
  Building wheel for oddity (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/geoff/anaconda3/envs/zwift/bin/python /home/geoff/anaconda3/envs/zwift/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmplvem8pnt
       cwd: /tmp/pip-req-build-f26w_2py
  Complete output (32 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/odditylib
  copying odditylib/decomp.py -> build/lib/odditylib
  copying odditylib/__init__.py -> build/lib/odditylib
  copying odditylib/detector.py -> build/lib/odditylib
  copying odditylib/collections.py -> build/lib/odditylib
  running egg_info
  writing oddity.egg-info/PKG-INFO
  writing dependency_links to oddity.egg-info/dependency_links.txt
  writing requirements to oddity.egg-info/requires.txt
  writing top-level names to oddity.egg-info/top_level.txt
  adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
  reading manifest file 'oddity.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'oddity.egg-info/SOURCES.txt'
  running build_ext
  running build_rust
  error: can't find Rust compiler
  
  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
  
  To update pip, run:
  
      pip install --upgrade pip
  
  and then retry package installation.
  
  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
  ----------------------------------------
  ERROR: Failed building wheel for oddity
Failed to build oddity
ERROR: Could not build wheels for oddity which use PEP 517 and cannot be installed directly

**Comment by Lleyton-Ariton** [comment]
It seems as though you don't have a rust compiler installed on your system.

Currently, Oddity does not come with pre-built binaries and builds them during installation. To build the binaries, you need a rust compiler before installing, download it from [here](https://www.rust-lang.org/tools/install)
